# Check on http://lint.travis-ci.org/ after modifying it!
# sudo: false
os:
  - linux
  # - osx
language: python
python:
  - "3.4"
  - "3.5"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION
  - source activate test_env
install:
  - conda install --yes -c https://conda.anaconda.org/biocore --file ci/conda_requirements.txt
  - pip install -r ci/pip_requirements.txt
  - pip install . --no-deps
script:
  - WITH_COVERAGE=TRUE make test
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/730436c08fd7f89462b0
    on_success: change
    on_failure: always
